apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-clean-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-clean-service
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-clean
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-clean
spec:
  selector:
    matchLabels:
      app: postgres-clean
  template:
    metadata:
      labels:
        app: postgres-clean
    spec:
      containers:
        - name: postgres-clean
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "telemetria_pulita"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "1234"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-clean-storage
      volumes:
        - name: postgres-clean-storage
          persistentVolumeClaim:
            claimName: postgres-clean-pvc
